[env:esp32-p4]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-p4
framework = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson@^7.4.2
  teemuatlut/TMCStepper@^0.7.3
  waspinator/AccelStepper@^1.64
  adafruit/Adafruit MAX31856 library@^1.2.5
  adafruit/Adafruit SHT4x Library@^1.0.5
  adafruit/Adafruit BME680 Library@^2.0.5
